const statecapitalindia = {
  "Andhra Pradesh": "Amaravati",
  "Arunachal Pradesh": "Itanagar",
  Assam: "Dispur",
  Bihar: "Patna",
  Chhattisgarh: "Raipur",
  Goa: "Panaji",
  Gujarat: "Gandhinagar",
  Haryana: "Chandigarh",
  "Himachal Pradesh": "Shimla",
  Jharkhand: "Ranchi",
  Karnataka: "Bengaluru",
  Kerala: "Thiruvananthapuram",
  "Madhya Pradesh": "Bhopal",
  Maharashtra: "Mumbai",
  Manipur: "Imphal",
  Meghalaya: "Shillong",
  Mizoram: "Aizawl",
  Nagaland: "Kohima",
  Odisha: "Bhubaneswar",
  Punjab: "Chandigarh",
  Rajasthan: "Jaipur",
  Sikkim: "Gangtok",
  "Tamil Nadu": "Chennai",
  Telangana: "Hyderabad",
  Tripura: "Agartala",
  "Uttar Pradesh": "Lucknow",
  Uttarakhand: "Dehradun",
  "West Bengal": "Kolkata",
};

const indianDams = {
  "Bhakra Nangal Dam": "Himachal Pradesh / Punjab",
  "Tehri Dam": "Uttarakhand",
  "Sardar Sarovar Dam": "Gujarat",
  "Hirakud Dam": "Odisha",
  "Nagarjuna Sagar Dam": "Telangana / Andhra Pradesh",
  "Indira Sagar Dam": "Madhya Pradesh",
  "Tungabhadra Dam": "Karnataka",
  "Mettur Dam": "Tamil Nadu",
  "Bhavanisagar Dam": "Tamil Nadu",
  "Koyna Dam": "Maharashtra",
  "Idukki Dam": "Kerala",
  "Rihand Dam": "Uttar Pradesh",
  "Maithon Dam": "Jharkhand",
  "Panchet Dam": "Jharkhand / West Bengal",
  "Dindi Dam": "Telangana",
  "Ukai Dam": "Gujarat",
  "Dholidhaja Dam": "Gujarat",
  "Krishna Raja Sagara Dam": "Karnataka",
  "Bargi Dam": "Madhya Pradesh",
  "Jayakwadi Dam": "Maharashtra",
};

const indianDamsrivernames = {
  "Bhakra Nangal Dam": "Sutlej River",
  "Tehri Dam": "Bhagirathi River",
  "Sardar Sarovar Dam": "Narmada River",
  "Hirakud Dam": "Mahanadi River",
  "Nagarjuna Sagar Dam": "Krishna River",
  "Indira Sagar Dam": "Narmada River",
  "Tungabhadra Dam": "Tungabhadra River",
  "Mettur Dam": "Cauvery River",
  "Bhavanisagar Dam": "Bhavani River",
  "Koyna Dam": "Koyna River",
  "Idukki Dam": "Periyar River",
  "Rihand Dam": "Rihand River (a tributary of Son River)",
  "Maithon Dam": "Barakar River",
  "Panchet Dam": "Damodar River",
  "Dindi Dam": "Dindi River (a tributary of Krishna River)",
  "Ukai Dam": "Tapti River",
  "Dholidhaja Dam": "Bhogavo River",
  "Krishna Raja Sagara Dam": "Cauvery River",
  "Bargi Dam": "Narmada River",
  "Jayakwadi Dam": "Godavari River",
};

const classicalDances = {
  Bharatanatyam: "Tamil Nadu",
  Kathak: "Uttar Pradesh",
  Kathakali: "Kerala",
  Kuchipudi: "Andhra Pradesh",
  Odissi: "Odisha",
  Manipuri: "Manipur",
  Mohiniyattam: "Kerala",
  Sattriya: "Assam",
  "Gaudiya Nritya": "West Bengal",
  Chhau: "Odisha / Jharkhand / West Bengal",
};

const folkDances = {
  Bihu: "Assam",
  Garba: "Gujarat",
  Ghoomar: "Rajasthan",
  Lavani: "Maharashtra",
  Bhangra: "Punjab",
  Rouf: "Jammu and Kashmir",
  "Dollu Kunitha": "Karnataka",
  Yakshagana: "Karnataka",
  Chhau: "Odisha / Jharkhand / West Bengal",
  Giddha: "Punjab",
  Kalbelia: "Rajasthan",
  Kummi: "Tamil Nadu",
  "Dandiya Raas": "Gujarat",
  Nati: "Himachal Pradesh",
  Hojagiri: "Tripura",
  Tippani: "Gujarat",
  Jhumar: "Jharkhand",
  Bagurumba: "Assam",
  Padayani: "Kerala",
  Kaikottikali: "Kerala",
};

const traditionalDances = {
  Bihu: "Assam",
  Ghoomar: "Rajasthan",
  Kalbelia: "Rajasthan",
  Garba: "Gujarat",
  "Dandiya Raas": "Gujarat",
  Lavani: "Maharashtra",
  Tamasha: "Maharashtra",
  Chhau: "Odisha / Jharkhand / West Bengal",
  Kummi: "Tamil Nadu",
  Kolattam: "Tamil Nadu",
  Karagattam: "Tamil Nadu",
  Theyyam: "Kerala",
  Padayani: "Kerala",
  Kaikottikali: "Kerala",
  Yakshagana: "Karnataka",
  "Dollu Kunitha": "Karnataka",
  "Thang Ta": "Manipur",
  Hojagiri: "Tripura",
  Jhumar: "Jharkhand",
  Bagurumba: "Assam",
  Domkach: "Bihar / Jharkhand",
  "Laho Dance": "Meghalaya",
  "Cheraw (Bamboo Dance)": "Mizoram",
};

const famousIndianBooksandauthors = {
  "The Discovery of India": "Jawaharlal Nehru",
  Gitanjali: "Rabindranath Tagore",
  "Midnight’s Children": "Salman Rushdie",
  "The God of Small Things": "Arundhati Roy",
  "Train to Pakistan": "Khushwant Singh",
  "A Suitable Boy": "Vikram Seth",
  "The Guide": "R. K. Narayan",
  "The White Tiger": "Aravind Adiga",
  "Interpreter of Maladies": "Jhumpa Lahiri",
  "In Custody": "Anita Desai",
  "The Palace of Illusions": "Chitra Banerjee Divakaruni",
  "Sea of Poppies": "Amitav Ghosh",
  "The Inheritance of Loss": "Kiran Desai",
  "Five Point Someone": "Chetan Bhagat",
  "An Era of Darkness": "Shashi Tharoor",
  "The Lowland": "Jhumpa Lahiri",
  "The Namesake": "Jhumpa Lahiri",
  "The Immortals of Meluha": "Amish Tripathi",
  "Rag Darbari": "Shrilal Shukla",
  "The Glass Palace": "Amitav Ghosh",
  "Serious Men": "Manu Joseph",
  "Fasting, Feasting": "Anita Desai",
  "A Fine Balance": "Rohinton Mistry",
  "The Room on the Roof": "Ruskin Bond",
  Narcopolis: "Jeet Thayil",
  "The Hungry Tide": "Amitav Ghosh",
  Yayati: "V. S. Khandekar",
  Rajtarangini: "Kalhana",
  Mritunjaya: "Shivaji Sawant",
  Malavikagnimitram: "Kalidasa",
  Shakuntala: "Kalidasa",
  Gora: "Rabindranath Tagore",
  Kanthapura: "Raja Rao",
};

const classicalDancers = {
  "Padma Subrahmanyam": "Bharatanatyam",
  "Birju Maharaj": "Kathak",
  "Rukmini Devi Arundale": "Bharatanatyam",
  "Guru Bipin Singh": "Manipuri",
  "Shovana Narayan": "Kathak",
  "Mallika Sarabhai": "Bharatanatyam",
  "Sonal Mansingh": "Odissi",
  "Kanak Rele": "Mohiniyattam",
  "Sitara Devi": "Kathak",
  "Uday Shankar": "Bharatanatyam",
  "Kelucharan Mohapatra": "Odissi",
  Swapnasundari: "Kuchipudi",
  "Jhaveri Sisters": "Manipuri",
  "Yamini Krishnamurthy": "Bharatanatyam",
  "Sanjukta Panigrahi": "Odissi",
  "Kalamandalam Krishnan Nair": "Kathakali",
  "Kalamandalam Kalyanikutty Amma": "Mohiniyattam",
  "Ramkrishna Talukdar": "Sattriya",
  "Rajkumar Singhajit Singh": "Sattriya",
  "Kalamandalam Gopi": "Kathakali",
  "Guru Gopinath": "Kathakali",
  "Guru Vempati Chinna Satyam": "Kuchipudi",
};

export const metadata = {
  statecapitalindia: {
    data: statecapitalindia,
    qline: "What is the capital of ____?",
    title: "Capital of states of India",
  },
  indianDams: {
    data: indianDams,
    qline: "____ is located in which state?",
    title: "Dams and their locations",
  },
  indianDamsrivernames: {
    data: indianDamsrivernames,
    qline: "____ is constructed on which river?",
    title: "Dams and their rivers",
  },
  classicalDances: {
    data: classicalDances,
    qline: "____ is danced in which state?",
    title: "Classical dances of India",
  },
  folkDances: {
    data: folkDances,
    qline: "____ is danced in which state?",
    title: "Folk dances of India",
  },
  traditionalDances: {
    data: traditionalDances,
    qline: "____ is danced in which state?",
    title: "Traditional dances of India",
  },
  famousIndianBooksandauthors: {
    data: famousIndianBooksandauthors,
    qline: "who is the author of ____?",
    title: "Famous Indian books and authors",
  },
  classicalDancers: {
    data: classicalDancers,
    qline: "____ is a famous dancer of which classical dance?",
    title: "Classical dancers of India",
  },
};
export const metadatafn = (name) => {
  return metadata[name] ? metadata[name] : null;
};
