import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Two min coding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7398670337880164"
          crossorigin="anonymous"
        ></Script>
      </head>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
